[platformio]
default_envs = universal_esp32

[env:universal_esp32]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs
board_build.partitions = partitions_ota.csv
board_build.psram = enabled

extra_scripts = pre:version_build.py, merge_bin.py

lib_deps =
    bblanchon/ArduinoJson @ ^7.4.3
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit NeoPixel @ ^1.12.3

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DMQTT_MAX_PACKET_SIZE=2048

monitor_filters =
    esp32_exception_decoder